
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

